import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "@/app/globals.css";
import NavBar from "@/components/Navbar";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className='dark'>
        <body className={inter.className}  style={{background: '#000', color: '#fff'}}>
        <NavBar/>
        {children}
        </body>
        </html>
    );
}
